### ISSUE TITLE
Kotlin/Native multi platform projects

### ISSUE THREAD

**Issue by joelhandwell** [jstuyts/kotlin-multiplatform-recipes#12]
[From v0.6 Kotlin/Native supports multi platform projects](https://blog.jetbrains.com/kotlin/2018/02/kotlinnative-v0-6-is-here/) which can be used for iOS application development. Is [Kotlin/Native multi platform project](https://github.com/JetBrains/kotlin-native/blob/master/MULTIPLATFORM.md) support included in the scope of this project?

**Comment by jstuyts** [comment]
No, not yet. And I currently don't have time to add it.

**Comment by joelhandwell** [comment]
@jstuyts thanks for clarification. Hope someone creates PR for this!
