### ISSUE TITLE
Wrong path for "Delegate  IDE build/run actions to gradle"

### ISSUE THREAD

**Issue by saied89** [jstuyts/kotlin-multiplatform-recipes#13]
In your list of Current Issues the path to _Delegate IDE build/run actions to gradle_ is wrong.
It might have changed recently but in 2018.2.4 its in _Build, Execution, Deployment_ >> _Build Tools_ >> _Gradle_ >> _Runner_

**Comment by jstuyts** [comment]
Thanks for reporting this. I corrected the path.
