### ISSUE TITLE
Emphasize build instructions 

### ISSUE THREAD

**Issue by yoavst** [jstuyts/kotlin-multiplatform-recipes#6]
```
Kotlin: Modifier 'impl' is only applicable to members that are initially declared in platform-independent code
```

Took me few times to read `README.md` to find the way to make build pass.

**Comment by jstuyts** [comment]
Could you elaborate what steps you took that lead to the error, and what you finally did to make the project build successfully? It is a regular Gradle project, so simply runing `./gradlew build` should work without errors.

**Comment by yoavst** [comment]
I'm talking about this part:
> You have to build and run the examples using the Gradle runner by enabling the following setting: Settings » Build, Execution, Deployment » Gradle » Runner » Delegate IDE build/run actions to gradle), or use the command line.

**Comment by yoavst** [comment]
Thanks for adding!
