### ISSUE TITLE
Test dependencies delegation

### ISSUE THREAD

**Issue by tarik02** [jstuyts/kotlin-multiplatform-recipes#9]
For example I have a project with modules:
 - jvm(jvm platform), `expectedBy project(':common')`
 - js(js platform), `expectedBy project(':common')`
 - common(common platform), `compile project(':util')`
 - util(common platform)

Then I want to add tests to util module, but the tests don't appear when i run `:js:test`. So i want to delegate tests. Thanks.

**Comment by tarik02** [comment]
... and there are issue that I can't use anything from module `util` in module `js`(and `jvm`) even if it is in dependencies of `common` and `js`(`compile project(':util')`)

**Comment by jstuyts** [comment]
I don't know how this is supposed to work. I think it is better if you ask on the [forum](https://discuss.kotlinlang.org/) or in channel #multiplatform on [Slack](https://kotlinlang.slack.com/).

It is a good use case though, and I will create a separate issue for it later.

**Comment by jstuyts** [comment]
I created #10.

**Comment by tarik02** [comment]
Thank you
